#ifndef LATTICE_CONFIG_H
#define LATTICE_CONFIG_H

#define LATTICE_NXMIN 0
#define LATTICE_NXMAX 0x000FFFFF
#define LATTICE_NYMIN 0
#define LATTICE_NYMAX 0x000FFFFF
#define LATTICE_NZMIN 0
#define LATTICE_NZMAX 0x000FFFFF
#define SECTOR_PER_SERVER_WIDTH_X 8
#define SECTOR_PER_SERVER_WIDTH_Y 8
#define SECTOR_PER_SERVER_WIDTH_Z 8
#define SECTOR_PER_SERVER_MASK_X 0xFF
#define SECTOR_PER_SERVER_MASK_Y 0xFF
#define SECTOR_PER_SERVER_MASK_Z 0xFF


#define WRITE_LENGTH 65536
#define READ_LENGTH 65536

#define MTU 512 // message size max (including (\r)\n\0)
#define MAX_ARGS MTU

// binary stuff

#define PACKET_MTU 512  // match this to MTU
#define PAYLOAD_MTU          (PACKET_MTU - sizeof(lt_packet_h))

#define SYNCH_MARKER  0xFFFFFFFF


#define SENDQ_BLOCK 262144

#define VISUAL_UNIT  32  // sectors
#define BURST_UNIT_MAX VISUAL_UNIT

#define SERVER_RETRY 120

#define SERVER_HANDSHAKE_TIMEOUT 30

#define SERVER_SEND_PING 120
#define SERVER_PING_TIMEOUT 60

#endif
