#ifndef LATTICE_CONFIG_H
#define LATTICE_CONFIG_H

#define LIBLATTICE_VERSION "0.3"

// address sizes MUST be the same across the entire network

// positional

#define LATTICE_NXMIN 0
#define LATTICE_NXMAX 0x001FFFFF
#define LATTICE_NYMIN 0
#define LATTICE_NYMAX 0x000FFFFF
#define LATTICE_NZMIN 0
#define LATTICE_NZMAX 0x001FFFFF
#define SECTOR_PER_SERVER_WIDTH_X 7
#define SECTOR_PER_SERVER_WIDTH_Y 8
#define SECTOR_PER_SERVER_WIDTH_Z 7
#define SECTOR_PER_SERVER_MASK_X 0x7F
#define SECTOR_PER_SERVER_MASK_Y 0xFF
#define SECTOR_PER_SERVER_MASK_Z 0x7F

// block database
#define BLOCKSDB_COUNT_WX 128
#define BLOCKSDB_COUNT_WY 32
#define BLOCKSDB_COUNT_WZ 128

#define BLOCKSDB_COUNT_BX 16
#define BLOCKSDB_COUNT_BY 8
#define BLOCKSDB_COUNT_BZ 16

#define BLOCKSDB_WIDTH_WX 7
#define BLOCKSDB_WIDTH_WY 5
#define BLOCKSDB_WIDTH_WZ 7

#define BLOCKSDB_WIDTH_BX 4
#define BLOCKSDB_WIDTH_BY 3
#define BLOCKSDB_WIDTH_BZ 4

#define BLOCKSDB_MASK_WX 0x7F
#define BLOCKSDB_MASK_WY 0x1F
#define BLOCKSDB_MASK_WZ 0x7F

#define BLOCKSDB_MASK_BX 0xF
#define BLOCKSDB_MASK_BY 0x7
#define BLOCKSDB_MASK_BZ 0xF

#define BLOCKSDB_SECTOR_COUNT (BLOCKSDB_COUNT_WX * BLOCKSDB_COUNT_WZ * BLOCKSDB_COUNT_WY)
#define BLOCKSDB_BLOCKS_COUNT (BLOCKSDB_COUNT_BY * BLOCKSDB_COUNT_BX * BLOCKSDB_COUNT_BZ)

#define BLOCKSDB_FLATDATA_COUNT (BLOCKSDB_COUNT_BX * BLOCKSDB_COUNT_BZ)
#define BLOCKSDB_FLATSECTOR_COUNT (BLOCKSDB_COUNT_WX * BLOCKSDB_COUNT_WZ)

#define BLOCKSDB_MAX_HARDSOLID 63

#define BLOCKSDB_HALFBLOCK_START  400

#define BLOCKSDB_AIR           0
#define BLOCKSDB_TORCH         820
#define BLOCKSDB_MOLTENSTONE   62
#define BLOCKSDB_LAVABLOCK     1001
#define BLOCKSDB_REDSTONE      43
#define BLOCKSDB_GREENSTONE    44
#define BLOCKSDB_FIRE          800
#define BLOCKSDB_LANTERN       552


#define WRITE_LENGTH 65536
#define READ_LENGTH 65536

#define MTU 10240 // message size max (including (\r)\n\0)
#define MAX_ARGS MTU

// binary stuff

#define PACKET_MTU 10240  // match this to MTU
#define PAYLOAD_MTU          (PACKET_MTU - sizeof(lt_packet_h))

#define SYNCH_MARKER  0xFFFFFFFF


#define SENDQ_BLOCK 262144

#define VISUAL_UNIT  32  // sectors
#define BURST_UNIT_MAX VISUAL_UNIT

#define SERVER_RETRY 120

#define SERVER_HANDSHAKE_TIMEOUT 30

#define SERVER_SEND_PING 120
#define SERVER_PING_TIMEOUT 60

#endif
